### ISSUE TITLE
ダイオードの向きについて

### ISSUE THREAD

**Issue by marby3** [suikagiken/suika85ergo#1]
購入者ではないのですが、偶然ビルドガイドをお見かけしたためissueを立てさせていただきました。

ダイオードの取り付け向きについて、ビルドガイド上ではこのように取り付けるとのことでしたが、
一般的？には逆向きのようです。
誤って取り付けてしまうケースがありそうな気がしました。
<img width="793" alt="image" src="https://github.com/suikagiken/suika85ergo/assets/64513524/141ad286-b5f9-4219-8b91-3a1cfe12197f">

意図的であれば、余計なお節介だと思って流してもらえれば幸いです。
よろしくお願いいたします。

**Comment by suikagiken** [comment]
ご指摘ありがとうございます。
おっしゃる通り、一般的な方向とは逆になってしまっていました。  
原因を調べたところ、フットプリントと逆のピン配置の回路記号を回路図の方に使用してしまっておりました。
（フットプリントは1=K 2=Aなのに、回路図は1=A 2=K）  
![image](https://github.com/suikagiken/suika85ergo/assets/115451678/c1b8a9c3-e4a0-46ee-8888-6ab875b78a44)

一方でファームウエアは回路図を信じて ```COL2ROW``` であるとして作成し、書き込んで出荷してしまったので、
このようなかたちにしております。

このガイドを参考に他のものを組み立ててしまったりすることがないように、
一般的な方向と逆であることを、図とビルドガイドに追記いたしました。
よろしくお願いいたします。
